### ISSUE TITLE
Hints Interface Support

### ISSUE THREAD

**Issue by cashaffer** [web-cat/code-workout#97] opened 2016-10-07 17:47 UTC
The YAML format for defining exercises has a field for giving hints. But  I see no interface for seeing a hint when doing a Code Workout exercise (at least not in the version as it appears within OpenDSA).

**Comment by pmk1433** [comment] 2016-10-07 17:51
Good point. I see the code in my development branch because I remember writing the code for it but somehow it is no longer in the master branch. 

https://github.com/web-cat/code-workout/blob/dev_krishnan/app/views/exercises/practice.html.haml

**Comment by s-edwards** [comment] 2016-10-18 15:01
I'm not sure where this comment comes from: "The YAML format for defining exercises has a field for giving hints".  I don't believe we've ever distributed any examples that include anything labeled "hints", and the importer doesn't accept any fields of any kind with that (or a related) name.  Can you be more specific?

Regarding Krishnan's comment, that code has never been merged with master/production/staging, since it doesn't work as intended, and doesn't follow the design results from Priyanka's thesis.  We still don't have a practical/useful design for supporting user-provided (or instructor-provided) "hints".

**Comment by cashaffer** [comment] 2016-10-18 18:36
> I'm not sure where this comment comes from:
> "The YAML format for defining exercises has a field for giving hints".

Hmmm... Now I am not sure why I thought that, sorry!

**Comment by s-edwards** [comment] 2016-10-18 19:00
We do have plans to support a hint-like infrastructure eventually, but it isn't fully developed yet.  I'll close this one, and we can take it up again when that feature set comes to the fore.  Thanks!

**Closed by s-edwards** 2016-10-18 19:00 UTC
